### ISSUE TITLE
Naming convention inconsistency: Rename wPressPlayText variable in title-screen-state.asm

### ISSUE THREAD

**Issue by CodeWithMa** [gbdev/gb-asm-tutorial#107]
In part 3 [title-screen](https://gbdev.io/gb-asm-tutorial/part3/title-screen.html) the variable `wPressPlayText` should not start with `w` as it is in ROM0.

https://github.com/gbdev/gb-asm-tutorial/blob/7c2b9c706652f4e095ca740e4f0c4023499b9f6b/galactic-armada/src/main/states/title-screen/title-screen-state.asm#L7

**Comment by ISSOtm** [comment]
Good catch, thank you!

Would you like to open a PR to fix this?

**Comment by CodeWithMa** [comment]
Sure I'll create a PR
