### ISSUE TITLE
Move the project under the gbdev umbrella

### ISSUE THREAD

**Issue by avivace** [gbdev/gb-asm-tutorial#18]
Only problem here would be setting up redirections (but we have already an instance of nginx running for homebrew hub so that would be just an additional site in that config)

- [x] Move the repository under gbdev/
- [x] Set up redirections

**Comment by tobiasvl** [comment]
Is this done?

**Comment by avivace** [comment]
Well not really, https://github.com/gbdev/gb-asm-tutorial/issues/51
