### ISSUE TITLE
Setup recommends old rgbds version

### ISSUE THREAD

**Issue by Rangi42** [gbdev/gb-asm-tutorial#35]
Setup says we will need "[RGBDS](https://rgbds.gbdev.io/install) v0.5.1 (though v0.5.0 should be compatible)". This should now say 0.6.1, even if it's compatible as far back as 0.5.0.

**Comment by ISSOtm** [comment]
The tutorial intentionally pins itself to a known-good version, and should be fully tested (preferably with `-Wall -Wextra`) with a given version before listing it.
