### ISSUE TITLE
Give less space to the "syntax-highlighting" paragraph in the README

### ISSUE THREAD

**Issue by avivace** [gbdev/gb-asm-tutorial#50]
This paragraph https://github.com/gbdev/gb-asm-tutorial#syntax-highlighting in the README is pretty confusing. It makes you think it's a mandatory step or something you need , while in reality it should just serve as reference on how that file is built/obtained, but most of the times it's not a useful information, we ship the build .js anyway in the repository..

Maybe move this into a separate .MD file? or at least mention when/how you would need to rebuild that

**Comment by ISSOtm** [comment]
Then that could get moved to a `README.md` next to the JS file.
