### ISSUE TITLE
Update old "ISSOtm/gb-asm-tutorial" links

### ISSUE THREAD

**Issue by avivace** [gbdev/gb-asm-tutorial#51]
- gb-asm-tutorial/src/part2/getting-started.md
- gb-asm-tutorial/src/index.md
- gb-asm-tutorial/src/help-feedback.md

have  ISSOtm/gb-asm-tutorial links which should be changed to gbdev/gb-asm-tutorial

**Comment by ISSOtm** [comment]
```shell
% find src -name '*.md' -exec sed -i 's,ISSOtm/gb-asm-tutorial,gbdev/gb-asm-tutorial,' {} +
```
