### ISSUE TITLE
Galactic Aramada Charmap Mapping Issue

### ISSUE THREAD

**Issue by walshyb** [gbdev/gb-asm-tutorial#78]
## Issue

In Galactic Armada, letters after "n" in the [text macro charmap](https://github.com/gbdev/gb-asm-tutorial/blob/7c400f9dec097dac54898d81497f62bdcc817740/galactic-armada/src/main/utils/macros/text-macros.inc) are offset by 1 because the there isn't a title dedicated to "O", it is shared with "0" at position 10. 

This makes it so when you load the game, instead of "PRESS A TO PLAY" under the title, you see "QSETT A UP QLAZ".

Output upon starting game:

<img width="370" alt="image" src="https://github.com/gbdev/gb-asm-tutorial/assets/6893300/4b028666-30c1-48cb-b5b6-b1dfb2659c87">

## Steps to reproduce

1. Clone gb-asm-tutorial repo
2. Change directory to `galactic-armada`
3. Run `make`
4. Open the `GalacticArmada.gb` file with your emulator of choice.

## Credit

Shout out to `pichu___.` on the gbdev Discord for helping find and solve the issue!

**Comment by walshyb** [comment]
Actually, issue was with my local setup! Accidentally created a tilemap alongside the `text-font.2bpp`, and when doing so it was also modifying the .2bpp somehow, making it so the tiles would be missing 1 tile (the "o").

I was getting this: 

![image](https://github.com/gbdev/gb-asm-tutorial/assets/6893300/9330c790-77fc-4337-a0d5-4330284ca47f)

<br><br>

Should look like this:
![image](https://github.com/gbdev/gb-asm-tutorial/assets/6893300/3e66f761-2291-4c10-8bde-27ba6705290c)

**Comment by ISSOtm** [comment]
Ah, good then; AIUI then there's nothing to be fixed on our end?
