### ISSUE TITLE
Misleading Entry Point 'main.asm' and 'xor' line preventing compilation

### ISSUE THREAD

**Issue by LaroldsJubilantJunkyard** [gbdev/gb-asm-tutorial#90]
Two issues pointed out by @bpf on the gbdev/asm-rgbds channel.

1. The 'main.asm' file is not the actual entrypoint, but that might be confusing for a lot of people. the actual entry point is the `src/main/GalacticArmada.asm` file. Code snippets should be adjusted to reflect this.
2. Getting an error of `syntax error, unexpected newline` in the enemies.asm file. There's a naked `xor` statement (no registers specified)

The discord messages for reference:

- https://discord.com/channels/303217943234215948/790920525253836912/1233463299941732363
- https://discord.com/channels/303217943234215948/790920525253836912/1233463392937709578

**Comment by avivace** [comment]
Is this fixed now @LaroldsJubilantJunkyard ?
